apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefuzz-sample-vac
  namespace: kubefuzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefuzz-sample-vac
  template:
    metadata:
      labels:
        app: kubefuzz-sample-vac
    spec:
      containers:
      - name: kubefuzz-vac
        image: registry.avolens.com/kubefuzz/sample_ac:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: kubefuzz-sample-vac
  namespace: kubefuzz
spec:
  selector:
    app: kubefuzz-sample-vac
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
