apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fooddeliveryorders.example.fuzz
spec:
  group: example.fuzz
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      price:
                        type: number
                    required:
                      - name
                      - price
                deliveryAddress:
                  type: string
                couponCode:
                  type: object
                  properties:
                    code:
                      type: string
                    discount:
                      type: integer
                status:
                  type: object
                  properties:
                    delivered:
                      type: boolean
                    payed:
                      type: boolean

  scope: Namespaced
  names:
    plural: fooddeliveryorders
    singular: fooddeliveryorder
    kind: FoodDeliveryOrder
    shortNames:
      - fdo
